info1:
  'billing_name': 'James Bond'
  'email': 'james.bond@gmail.com'
  'tel': '123-456-7890'
  'billing_address': '1 Times Square'
  'billing_address_2': '321'
  'billing_zip': '10036'
  'billing_city': 'New York'
  'billing_state': 'NY'
  'billing_country': 'USA'
  'nlb': '1234 5678 8901 2345'
  'month': '01'
  'year': '2021'
  'rvv': '666'

info2:
  'billing_name': 'Jane Bond'
  'email': 'jane.bond@gmail.com'
  'tel': '987-654-3210'
  'billing_address': '2 Divide Circle'
  'billing_address_2': '123'
  'billing_zip': '10036'
  'billing_city': 'New York'
  'billing_state': 'NY'
  'billing_country': 'USA'
  'nlb': '1234 5678 8901 2345'
  'month': '12'
  'year': '2023'
  'rvv': '999'
